tasks:
  - recogition_eval

recogition_eval:  # Table
  metrics:
    - TEDS
    - Edit_dist
  dataset:
    dataset_name: recogition_table_dataset
    ground_truth:
      data_path: /mnt/petrelfs/ouyanglinke/PDF-Extract-Kit-v2/pdf_validation/test_data/table_recog/table_gt.json
    prediction:
      data_path: /mnt/petrelfs/ouyanglinke/PDF-Extract-Kit-v2/pdf_validation/test_data/table_recog/table_pred.json
