inputs: assets/demo/formula_detection_pdfs
outputs: outputs/formula_detection_pdfs
tasks:
  formula_detection:
    model: formula_detection_yolo
    model_config:
      img_size: 1280
      conf_thres: 0.25
      iou_thres: 0.45
      model_path: models/MFD/weights.pt
      visualize: True
  formula_recognition:
    model: formula_recognition_unimernet
    model_config:
      cfg_path: pdf_extract_kit/configs/unimernet.yaml
      model_path: models/MFR/UniMERNet
      visualize: True