inputs: assets/demo/formula_detection
outputs: outputs/formula_detection
tasks:
  formula_detection:
    model: formula_detection_yolo
    model_config:
      img_size: 1280
      conf_thres: 0.25
      iou_thres: 0.45
      batch_size: 2
      model_path: /mnt/petrelfs/zhaozhiyuan/layout/PDF-Extract-Kit-v2/weights.pt
      visualize: True
      rect: True
      device: "0"