inputs: assets/demo/layout_detection
outputs: outputs/layout_detection
tasks:
  layout_detection:
    model: layout_detection_yolo
    model_config:
      img_size: 1280
      conf_thres: 0.25
      iou_thres: 0.45
      batch_size: 2
      model_path: /mnt/hwfile/opendatalab/zhaozhiyuan/PDF-Extract-Kit-v2-models/yolov10m_0830_mixed_epoch500_imgsz1280_bs64_pretrain_None/weights/best.pt
      visualize: True
      rect: True
      device: "0"